
4. TO - DO - Task

Please complete all the problem listed below.
4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}



In [2]:
import numpy as np

# 1.
empty_array = np.empty((2, 2))
print("1. Empty Array (2x2):\n", empty_array)

# 2.
ones_array = np.ones((4, 2))
print("\n2. All-One Array (4x2):\n", ones_array)

# 3.
fill_value = 7
filled_array = np.full((3, 3), fill_value)
print("\n3. Array filled with value 7 (3x3):\n", filled_array)

# 4.
given_array = np.array([[2, 4], [6, 8]])
zeros_like_array = np.zeros_like(given_array)
print("\n4. Zeros Array (Same shape as given array):\n", zeros_like_array)

# 5.
ones_like_array = np.ones_like(given_array)
print("\n5. Ones Array (Same shape as given array):\n", ones_like_array)

# 6.
new_list = [1, 2, 3, 4]
converted_array = np.array(new_list)
print("\n6. Converted Numpy Array from list [1, 2, 3, 4]:\n", converted_array)


1. Empty Array (2x2):
 [[4.94738513e-310 0.00000000e+000]
 [            nan 2.73610137e-310]]

2. All-One Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with value 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros Array (Same shape as given array):
 [[0 0]
 [0 0]]

5. Ones Array (Same shape as given array):
 [[1 1]
 [1 1]]

6. Converted Numpy Array from list [1, 2, 3, 4]:
 [1 2 3 4]


4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [3]:
import numpy as np

# 1.
array_range = np.arange(10, 50)
print("1. Array ranging from 10 to 49:\n", array_range)

# 2.
matrix_3x3 = np.arange(9).reshape((3, 3))
print("\n2. 3x3 Matrix (values from 0 to 8):\n", matrix_3x3)

# 3.
identity_matrix = np.eye(3)
print("\n3. 3x3 Identity Matrix:\n", identity_matrix)

# 4.
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\n4. Random Array (size 30):\n", random_array)
print("Mean of the array:", mean_value)

# 5.
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n5. 10x10 Random Array:\n", random_10x10)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

# 6.
zero_array = np.zeros(10)
zero_array[4] = 1
print("\n6. Zero Array with 5th element replaced by 1:\n", zero_array)

# 7.
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_array = arr[::-1]
print("\n7. Reversed Array:\n", reversed_array)

# 8.
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n8. 2D Array with 1 on border and 0 inside:\n", border_array)

# 9.
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[::2, 1::2] = 1
checkerboard[1::2, ::2] = 1
print("\n9. 8x8 Checkerboard Pattern:\n", checkerboard)


1. Array ranging from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 Matrix (values from 0 to 8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random Array (size 30):
 [0.50884119 0.66893778 0.0021739  0.33957855 0.41243947 0.8600198
 0.74497938 0.33808646 0.04334908 0.06619848 0.73581708 0.16918221
 0.94880979 0.0641098  0.07732786 0.46170225 0.69788932 0.79233859
 0.93224505 0.7313383  0.96609481 0.59924294 0.23396794 0.26042083
 0.3820124  0.35285605 0.22940041 0.69351445 0.17926242 0.32388621]
Mean of the array: 0.46053409334687045

5. 10x10 Random Array:
 [[0.54665455 0.03747451 0.16493594 0.2843532  0.8622643  0.61593669
  0.14471132 0.01131226 0.58140059 0.61573672]
 [0.46122165 0.04848443 0.77303975 0.91368091 0.02007091 0.27745487
  0.67890308 0.64878377 0.47660543 0.41811411]
 [0.85073895 0.85734739 0.99913596 0.2136049  0.59031198 

Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [6]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1.
array_sum = x + y
print("1. ")
print("Array Addition (x + y):\n", array_sum)

# 2.
array_diff = x - y
print("\n2.")
print("\nArray Subtraction (x - y):\n", array_diff)

# 3.
integer = 3
array_mul = x * integer
print("\n3. ")
print("\nArray Multiplication (x * 3):\n", array_mul)

# 4.
array_square = np.square(x)
print("\n4. ")
print("\nSquare of elements in array x:\n", array_square)

# 5.
dot_vw = np.dot(v, w)
print("\n5. ")
print("\nDot product of v and w:", dot_vw)

dot_xv = np.dot(x, v)
print("Dot product of x and v:\n", dot_xv)

dot_xy = np.dot(x, y)
print("Dot product of x and y:\n", dot_xy)

# 6.
concat_xy = np.concatenate((x, y), axis=0)
print("\n6. ")
print("\nConcatenation of x and y along rows:\n", concat_xy)

concat_vw = np.column_stack((v, w))
print("\nConcatenation of v and w along columns:\n", concat_vw)

# 7.
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\nConcatenation of x and v along rows:\n", concat_xv)
except ValueError as e:
    print("\nError in concatenation of x and v:\n", e)


1. 
Array Addition (x + y):
 [[ 6  8]
 [10 13]]

2.

Array Subtraction (x - y):
 [[-4 -4]
 [-4 -3]]

3. 

Array Multiplication (x * 3):
 [[ 3  6]
 [ 9 15]]

4. 

Square of elements in array x:
 [[ 1  4]
 [ 9 25]]

5. 

Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]

6. 

Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
 [[ 9 11]
 [10 12]]

Error in concatenation of x and v:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [7]:
import numpy as np

# Given Matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A⁻¹ = I
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A.A⁻¹ = I:\n", identity_matrix)

# Round to eliminate numerical precision errors
identity_matrix_rounded = np.round(identity_matrix, decimals=10)
print("\nRounded Identity Matrix:\n", identity_matrix_rounded)

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("\nBA:\n", BA)
print("\nAB ≠ BA:", not np.array_equal(AB, BA))

# 3. Prove (AB)ᵀ = BᵀAᵀ
AB_transpose = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)
print("\n(AB)ᵀ:\n", AB_transpose)
print("\nBᵀAᵀ:\n", BT_AT)
print("\n(AB)ᵀ == BᵀAᵀ:", np.array_equal(AB_transpose, BT_AT))


A.A⁻¹ = I:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Rounded Identity Matrix:
 [[1. 0.]
 [0. 1.]]

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

AB ≠ BA: True

(AB)ᵀ:
 [[23 51]
 [13 29]]

BᵀAᵀ:
 [[23 51]
 [13 29]]

(AB)ᵀ == BᵀAᵀ: True


4.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import numpy as np
import time

# Helper function to measure execution time
def measure_time(func, *args):
    start = time.time()
    result = func(*args)
    end = time.time()
    return result, end - start

# 1. Element-wise Addition
# Python lists
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

def python_addition(a, b):
    return [a[i] + b[i] for i in range(len(a))]

_, python_add_time = measure_time(python_addition, list1, list2)
print(f"Python List Addition Time: {python_add_time:.5f} seconds")

# NumPy arrays
array1 = np.arange(size)
array2 = np.arange(size)

def numpy_addition(a, b):
    return a + b

_, numpy_add_time = measure_time(numpy_addition, array1, array2)
print(f"NumPy Array Addition Time: {numpy_add_time:.5f} seconds")

2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [9]:
import numpy as np
import time

def measure_time(func, *args):
    start = time.time()
    result = func(*args)
    end = time.time()
    return result, end - start

size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

array1 = np.arange(size)
array2 = np.arange(size)

# Python list multiplication
def python_multiplication(a, b):
    return [a[i] * b[i] for i in range(len(a))]

_, python_mul_time = measure_time(python_multiplication, list1, list2)
print(f"Python List Multiplication Time: {python_mul_time:.5f} seconds")

# NumPy array multiplication
def numpy_multiplication(a, b):
    return a * b

_, numpy_mul_time = measure_time(numpy_multiplication, array1, array2)
print(f"NumPy Array Multiplication Time: {numpy_mul_time:.5f} seconds")


Python List Multiplication Time: 0.13081 seconds
NumPy Array Multiplication Time: 0.00548 seconds


3. Dot Product

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [10]:
import numpy as np
import time
def python_dot_product(a, b):
    return sum(a[i] * b[i] for i in range(len(a)))

_, python_dot_time = measure_time(python_dot_product, list1, list2)
print(f"Python List Dot Product Time: {python_dot_time:.5f} seconds")

# NumPy arrays
def numpy_dot_product(a, b):
    return np.dot(a, b)

_, numpy_dot_time = measure_time(numpy_dot_product, array1, array2)
print(f"NumPy Array Dot Product Time: {numpy_dot_time:.5f} seconds")

Python List Dot Product Time: 0.15475 seconds
NumPy Array Dot Product Time: 0.00193 seconds


4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [12]:
import numpy as np
import time

def measure_time(func, *args):
    start = time.time()
    result = func(*args)
    end = time.time()
    return result, end - start

size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

array1 = np.arange(size)
array2 = np.arange(size)

# Python list multiplication
def python_multiplication(a, b):
    return [a[i] * b[i] for i in range(len(a))]

_, python_mul_time = measure_time(python_multiplication, list1, list2)
print(f"Python List Multiplication Time: {python_mul_time:.5f} seconds")

# NumPy array multiplication
def numpy_multiplication(a, b):
    return a * b

_, numpy_mul_time = measure_time(numpy_multiplication, array1, array2)
print(f"NumPy Array Multiplication Time: {numpy_mul_time:.5f} seconds")


Python List Multiplication Time: 0.22745 seconds
NumPy Array Multiplication Time: 0.00473 seconds
